version: '3'
services:
  copypasta_db:
    image: postgres
    container_name: copypasta_db 
    restart: unless-stopped
    environment:
      - POSTGRES_DB=backend_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -d postgres
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 5s
    volumes:
      - ./pgdata_copypasta:/var/lib/postgres/data
    networks:
      - copypasta_network
 
  copypasta:
    build: ./copypasta/
    container_name: backend
    ports:
      - 8000:8000
    environment:
          - DB_CONNECTION=pgsql
          - DB_HOST=db
          - DB_PORT=5432
          - DB_DATABASE=backend_db
          - DB_USERNAME=user
    networks:
      - copypasta_network

  keycloak_db:
    image: postgres
    container_name: keycloak_db 
    restart: unless-stopped
    environment:
      - POSTGRES_DB=keycloak_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - 5433:5432
    healthcheck:
      test: pg_isready -d postgres
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 5s
    volumes:
      - ./pgdata_keycloak:/var/lib/postgres/data
    networks:
      - keycloak_network

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:22.0.4
    build:
      context: .
      args:
        KEYCLOAK_VERSION: 22.0.0
    depends_on:
      - keycloak_db
    ports:
      - 8080:8080
      - 8187:8187
    environment:
      JAVA_OPTS_APPEND: -Dkeycloak.profile.feature.upload_scripts=enabled
      KC_HOSTNAME_URL: http://localhost:8080
      KC_DB_PASSWORD: password 
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/keycloak_db
      KC_DB_USERNAME: user 
      KC_HEALTH_ENABLED: 'true'
      KC_HTTP_ENABLED: 'true'
      KC_METRICS_ENABLED: 'true'
      KC_PROXY: reencrypt
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    command: 
      - start --auto-build --db postgres --hostname-strict-https false --hostname-strict false --proxy edge --http-enabled true --import-realm --spi-user-profile-legacy-user-profile-read-only-attributes *_RES_ACCESS_MODE

    networks:
      - keycloak_network

networks:
  copypasta_network:
  keycloak_network:
    driver: bridge
