version: '3'
services:
  copypasta_db:
    image: postgres
    container_name: copypasta_db 
    restart: unless-stopped
    environment:
      - POSTGRES_DB=backend_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -d postgres
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 5s
    volumes:
      - ./pgdata_copypasta:/var/lib/postgres/data
    networks:
        - mynet

  copypasta:
    build: ./copypasta/
    container_name: backend
    ports:
      - 8000:8000
    environment:
          - DB_CONNECTION=pgsql
          - DB_HOST=db
          - DB_PORT=5432
          - DB_DATABASE=backend_db
          - DB_USERNAME=user
    networks:
        - mynet
  
  keycloack:
    image: quay.io/keycloak/keycloak:22.0.4
    ports:
      - 8080:8080
    environment:
      - KEYCLOACK_ADMIN = admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
   
networks:
    mynet:
      name: shared-db
